---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ${CONTAINER_IMAGE}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: ${CONTAINER_IMAGE}
  template:
    metadata:
      labels:
        app: ${CONTAINER_IMAGE}
    spec:
      nodeSelector:
        ${NODE_SELECTOR}
      containers:
        - name: ${CONTAINER_IMAGE}
          image: reg.trendmatch.dk/kollekt/${CONTAINER_IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 700m
              memory: 800Mi
            requests:
              cpu: 200m
              memory: 250Mi
      imagePullSecrets:
        - name: dashboard-regcred
      
      terminationGracePeriodSeconds: 30
