---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ${CONTAINER_IMAGE}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: ${CONTAINER_IMAGE}
  template:
    metadata:
      labels:
        app: ${CONTAINER_IMAGE}
    spec:
      containers:
        - name: ${CONTAINER_IMAGE}
          image: reg.trendmatch.dk/kollekt/${CONTAINER_IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: env-file
              mountPath: /app/.env
              subPath: .env
      volumes:
        - name: env-file
          configMap: 
            name: dashboard-env
      
      terminationGracePeriodSeconds: 30