---
apiVersion: v1
kind: Service
metadata:
  name: ${CONTAINER_IMAGE}
  labels:
    app: ${CONTAINER_IMAGE}
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: ${CONTAINER_IMAGE}  