@extends('layouts.app')

@section('content')
<div class="container legal">
    
    <p>Effective as of September 13, 2019</p>
    <p>Trendmatch ApS ("Trendmatch,&rdquo;Trendmatch-Kollekt&rdquo;,&rdquo;Kollekt&rdquo;," "we," "us," or "our") welcomes you. Thank you for choosing to access and use our service (the "Service") made available to you through our website located at&nbsp;<a href="http://kollekt-app.azurewebsites.net">http://kollekt-app.azurewebsites.net</a> &nbsp;(the "Website") or through our mobile application (the "App").</p>
    <p>We provide access to and use of our Service subject to the following terms of service (the "Terms of Service"), which are effective as of the date stated above, unless a separate contract is in place. In case of a separate contract it will be the primary agreement, and these terms will only be referred to should the contract not contain anything regarding the issue.</p>
    <p>By using the Service, you acknowledge that you have read, understood, and agree to be legally bound by the terms and conditions of these Terms of Service and the terms and conditions of our Privacy Policy, which is hereby incorporated by reference. Please take the time to review our Privacy Policy. If you do not agree to any terms in these Terms of Service or the Privacy Policy, then please do not use our Service.</p>
    <p>You can find the privacy policy here: <a href="{{URL::to('/')}}/privacy-policy">{{URL::to('/')}}/privacy-policy</a></p>
    <p>We may change these Terms of Service from time to time and will post any changes on the Website or notify you via email, at our option, as soon as such changes are in effect. If you are using the Service on a free trial basis, then by continuing to use the Service after we make any such changes to the Terms of Service, you are deemed to have accepted such changes. If you have purchased a Service subscription, then the changes will not go into effect until your Service subscription renews. Please refer to these Terms of Service on a regular basis.</p>
    <p><strong>Access and Use</strong></p>
    <p>Subject to the terms and conditions of this Agreement, Trendmatch-Kollekt will provide access to and use of the Service to you or the entity which you have authority to bind to this Agreement ("Subscriber"). We will also provide access to and use of the Service to any employee of Subscriber or other individual authorized by Subscriber (each, an "Authorized User"). Subscriber acknowledges that each Authorized User must agree to these Terms of Service and the Privacy Policy prior to use and that Subscriber shall be responsible for ensuring compliance by each Authorized User with these Terms of Service and for any breach of these Terms of Service by any Authorized User.</p>
    <p>Subscriber is solely responsible for any data or content uploaded or stored on the Service by Subscriber or any Authorized User ("Subscriber Data"). In no event shall Trendmatch-Kollekt be responsible for the use or misuse of any Subscriber Data by Subscriber or any Authorized User or other third party. Subscriber warrants and represents that it either owns or has the right to provide all Subscriber Data. Subscriber hereby grants Trendmatch-Kollekt a non-exclusive, transferable, royalty-free license to use the Subscriber Data to provide the Service and as otherwise described in herein or in our Privacy Policy. As stated in the Privacy Policy, we take reasonable steps to protect the Subscriber Data from loss, misuse, and unauthorized access, disclosure, alteration, or destruction. For the avoidance of doubt, in no event will we share the project information that you upload into the Service with third parties for marketing or other purposes not requested by the subscriber.</p>
    <p>All right, title, and interest in and to the Service, the Website, the App, and any information, data, software, graphics, and interactive features contained therein, including all modifications, improvements, adaptations, enhancements, or translations made thereto, and all proprietary rights in any of the foregoing (collectively, "Kollekt Property"), shall be and remain the sole and exclusive property of Trendmatch-Kollekt.</p>
    <p>Subscriber will not, and will not permit any Authorized User or other third party to: (i) allow anyone other than an Authorized User to access or use the Service; (ii) use the Service in any way that is not expressly permitted by this Agreement, including, without limitation, reverse engineering, modifying, copying, distributing, or sublicensing the Service, or introducing into the Service any software, virus, or code; or (iii) use the Service in violation of any applicable law or regulation.</p>
    <p><strong>Registration</strong></p>
    <p>Prior to using the Service, Subscriber will be required to register for an account. During the registration process, Subscriber will select logon credentials for each Authorized User. Logon credentials can only be used by the Authorized User to whom they are assigned and cannot be shared among Authorized Users or with third parties. Subscriber is solely responsible for the confidentiality and use of all logon credentials for its account and those assigned to Authorized Users, as well as for any use or misuse of the Service using Subscriber's or any Authorized User's logon credentials. Subscriber shall notify us immediately if it becomes aware of any loss, theft or unauthorized use of any logon credentials, and we reserve the right to delete or change them at any time and for any reason.</p>
    <p><strong>Fees and Payment</strong></p>
    <p>In consideration for the access to and use of the Service, you shall pay Trendmatch-Kollekt the fees determined according to the payment plan that you have selected at registration. You must provide accurate information regarding your credit card or other payment instrument, and you must promptly update your payment information if such information changes. You hereby authorize Trendmatch-Kollekt to periodically bill your payment instrument in advance, in accordance with the payment plan you have selected. If you wish to dispute any charges, you must provide notice to Kollekt of such dispute within sixty (60) days of payment of the disputed charge. All amounts paid are non-refundable.</p>
    <p>We reserve the right to change our prices at any point. If we do change prices, we will provide notice to you through the Website or via email, at our option, at least thirty (30) days before such change is to take effect. Your continued use of the Service after the price change constitutes your agreement to pay the changed amount; provided, however, that if you have purchased an annual Service subscription, the price change will not go into effect until the end of your then-current subscription period.</p>
    <p><strong>Term and Termination</strong></p>
    <p>Trendmatch-Kollekt may suspend or terminate your access to and use of the Service, in whole or in part, at any time and for deliberate breach of these terms of service. You may terminate your account at any time upon notice to us; provided, however, that if you have purchased a subscription for the Service, your right to terminate your account before paying the full amount of fees for the subscription period that you have committed to will be limited to cases where Trendmatch-Kollekt has breached these Terms of Service, and has not cured such breach within 10 business days of receiving written notice of such breach from you. In the event of suspension or termination. Trendmatch will provide you with access to your Subscriber Data for at least 30 days following such termination. It is your responsibility to keep backup copies of the Subscriber Data.</p>
    <p><strong>DISCLAIMERS; LIMITED WARRANTY</strong></p>
    <p>THE KOLLEKT PROPERTY IS PROVIDED "AS IS" AND "AS AVAILABLE," AND TRENDMATCH-KOLLEKT DOES NOT MAKE ANY WARRANTIES WITH RESPECT TO THE SAME OR OTHERWISE IN CONNECTION WITH THESE TERMS OF SERVICE AND HEREBY DISCLAIMS ANY AND ALL EXPRESS, IMPLIED, OR STATUTORY WARRANTIES, INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AVAILABILITY, ERROR-FREE OR UNINTERRUPTED OPERATION, AND ANY WARRANTIES ARISING FROM A COURSE OF DEALING, COURSE OF PERFORMANCE, OR USAGE OF TRADE. TO THE EXTENT THAT TRENDMATCH-KOLLEKT MAY NOT AS A MATTER OF APPLICABLE LAW DISCLAIM ANY IMPLIED WARRANTY, THE SCOPE AND DURATION OF SUCH WARRANTY WILL BE THE MINIMUM PERMITTED UNDER SUCH LAW.</p>
    <p><strong>LIMITATION OF LIABILITY</strong></p>
    <p>IN NO EVENT WILL TRENDMATCH-KOLLEKT BE LIABLE TO SUBSCRIBER OR ANY OTHER PARTY, INCLUDING, WITHOUT LIMITATION, ANY AUTHORIZED USER, FOR ANY INCIDENTAL, INDIRECT, CONSEQUENTIAL, SPECIAL, EXEMPLARY, OR PUNITIVE DAMAGES OF ANY KIND (INCLUDING, BUT NOT LIMITED TO, LOST REVENUES OR PROFITS) ARISING FROM OR RELATING TO THE KOLLEKT PROPERTY OR OTHERWISE RELATING TO THESE TERMS OF SERVICE, REGARDLESS OF WHETHER TRENDMATCH-KOLLEKT WAS ADVISED, HAD OTHER REASON TO KNOW, OR IN FACT KNEW OF THE POSSIBILITY THEREOF. TRENDMATCH-KOLLEKT&rsquo;S AGGREGATE LIABILITY FOR DIRECT DAMAGES UNDER THESE TERMS OF SERVICE WILL NOT EXCEED THE TOTAL FEES PAID BY SUBSCRIBER HEREUNDER DURING THE SIX (6) MONTHS IMMEDIATELY PRIOR TO THE EVENT GIVING RISE TO THE CLAIM.</p>
    <p><strong>Indemnification</strong></p>
    <p>Subscriber will defend, indemnify, and hold harmless Trendmatch-Kollekt and its officers, directors, managers, and employees from any and all liabilities, costs, and expenses (including, without limitation, reasonable attorneys' fees) in connection with any third-party claim that any of the Subscriber Data: (i) infringes or misappropriates any third-party intellectual property rights, privacy or publicity rights, or any other rights; or (ii) violates any applicable laws, rules, or regulations. Kollekt shall promptly notify Subscriber of the claim, provided, however, that failure to provide such notice shall not relieve Subscriber of its indemnity obligations unless it is materially prejudiced thereby. Subscriber shall have control over the defense of the claim, provided that (i) Subscriber does not make any admission of liability on behalf of Trendmatch-Kollekt or agree to any settlement that imposes a financial burden on Trendmatch-Kollekt without Trendmatch-Kollekt&rsquo;s prior written consent; and (ii) Kollekt shall have the right to participate in the defense of any such claim, at its own cost, with counsel of its choice.</p>
    <p><strong>General Provisions</strong></p>
    <p>Subscriber shall not assign these Terms of Service or any of its rights hereunder without the prior, written consent of Kollekt. Subject to the foregoing, this Agreement will be binding upon and inure to the benefit of the Parties hereto and their permitted successors and assigns. These Terms of Service and performance hereunder shall be construed and governed by the laws of Denmark. The parties consent and agree that any and all litigation between them arising from these Terms of Service or the business relationship created hereby shall take place in the Danish courts. Each Party irrevocably consents and submits to the jurisdiction and venue of any such courts. If any provision of these Terms of Service is deemed invalid or unenforceable, it shall be amended or replaced in the way that best reflects the original intention of the parties, and the remainder of these Terms of Service shall remain in full force and effect. These Terms of Service, together with the Privacy Policy and any pricing information made known to you at registration, constitute the final and complete agreement between the parties regarding the subject matter hereof, and supersedes any prior or contemporaneous communications, representations, or agreements between the parties, whether oral or written.</p>
    <p>&nbsp;</p>

</div>
@endsection