name: Deployment

on:
  push:
    branches:
      - new_release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo 'Checkout done!!!'
    - run: echo ${{ secrets.DEV_ENV }} | base64 --decode > .env
    - name: Install php library
      uses: MilesChou/composer-action@v1.0.1
      with:
        args: install --no-dev

    - name: Build vuejs
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run production
    - run: rm -rf node_modules

    - uses: azure/docker-login@v1
      with:
        login-server: reg.trendmatch.dk
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build the Docker
      run: docker build . --file Dockerfile --tag reg.trendmatch.dk/kollekt/kollekt-dev-dashboard:${{ github.sha }}

    - name: Push docker image
      run: docker push reg.trendmatch.dk/kollekt/kollekt-dev-dashboard:${{ github.sha }}
    
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEV_HOST }}
        username: ${{ secrets.HOST_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker stop kollekt-dev-dashboard || true 
          docker rm kollekt-dev-dashboard || true
          docker run -d --name kollekt-dev-dashboard -p 29180:8080 reg.trendmatch.dk/kollekt/kollekt-dev-dashboard:${{ github.sha }}
          docker image prune -af